using Microsoft.EntityFrameworkCore;
using SecureVault.Core.Entities;
using SecureVault.Core.Enums;
using SecureVault.Core.Interfaces;
using SecureVault.Infrastructure.Data;

namespace SecureVault.Api.Services;

/// <summary>
/// Handles first-run system initialization: Super Admin user and root folder.
/// The MEK and JWT signing key MUST be pre-generated by the operator and placed
/// under C:\ProgramData\SecureVault\secrets\ with NTFS ACLs that grant read-only
/// access to the SecureVault service account, before the application starts — they are loaded
/// once at startup by EncryptionService and the JWT bearer pipeline.
/// </summary>
public class FirstRunService
{
    private static readonly SemaphoreSlim InitializationLock = new(1, 1);

    private readonly IDbContextFactory<AppDbContext> _dbFactory;
    private readonly IEncryptionService _encryption;
    private readonly IAuditService _audit;
    private readonly ILogger<FirstRunService> _logger;

    public FirstRunService(
        IDbContextFactory<AppDbContext> dbFactory,
        IEncryptionService encryption,
        IAuditService audit,
        ILogger<FirstRunService> logger)
    {
        _dbFactory = dbFactory;
        _encryption = encryption;
        _audit = audit;
        _logger = logger;
    }

    public async Task<bool> IsInitializedAsync(CancellationToken ct = default)
    {
        await using var db = await _dbFactory.CreateDbContextAsync(ct);
        return await db.SystemStates.AnyAsync(s => s.IsInitialized, ct);
    }

    public async Task InitializeAsync(
        string adminUsername,
        string adminEmail,
        string adminPassword,
        CancellationToken ct = default)
    {
        await InitializationLock.WaitAsync(ct);
        try
        {
            await using var db = await _dbFactory.CreateDbContextAsync(ct);
            await using var transaction = await db.Database.BeginTransactionAsync(ct);

            // Serialize setup across every application instance. The static semaphore
            // handles this process; sp_getapplock covers other processes or servers.
            await db.Database.ExecuteSqlRawAsync(
                "DECLARE @result int; " +
                "EXEC @result = sp_getapplock @Resource = N'SecureVault.FirstRun', " +
                "@LockMode = N'Exclusive', @LockOwner = N'Transaction', @LockTimeout = 15000; " +
                "IF @result < 0 THROW 51000, 'Unable to acquire initialization lock.', 1;",
                ct);

            // Double-check inside lock
            if (await db.SystemStates.AnyAsync(s => s.IsInitialized, ct))
                throw new InvalidOperationException("System is already initialized.");

            ValidatePasswordStrength(adminPassword);

            // The MEK and JWT signing key are loaded at application startup. If the app
            // reached this code, both keys are already present and valid — nothing to
            // generate here. The operator is responsible for provisioning them per
            // INSTALL.md before the SecureVault Windows service is started.

            // Create Super Admin user
            var admin = new User
            {
                Id = Guid.NewGuid(),
                Username = adminUsername,
                Email = adminEmail,
                PasswordHash = _encryption.HashPassword(adminPassword),
                IsSuperAdmin = true,
                IsActive = true,
                CreatedAt = DateTimeOffset.UtcNow,
                UpdatedAt = DateTimeOffset.UtcNow
            };
            db.Users.Add(admin);

            // Create root folder
            var rootFolder = new Folder
            {
                Id = Guid.NewGuid(),
                Name = "Root",
                ParentFolderId = null,
                Depth = 0,
                CreatedAt = DateTimeOffset.UtcNow,
                UpdatedAt = DateTimeOffset.UtcNow
            };
            db.Folders.Add(rootFolder);

            var state = await db.SystemStates.SingleAsync(s => s.Id == 1, ct);
            state.IsInitialized = true;
            db.AuditLogs.Add(new AuditLog { Action = AuditAction.SystemInitialized,
                ActorUserId = admin.Id, ActorUsername = admin.Username, EventTime = DateTimeOffset.UtcNow });
            await db.SaveChangesAsync(ct);
            await transaction.CommitAsync(ct);

            _logger.LogInformation("SecureVault initialization complete. Admin user: {Username}", adminUsername);
        }
        finally
        {
            InitializationLock.Release();
        }
    }

    private static void ValidatePasswordStrength(string password)
    {
        if (password.Length < 12)
            throw new InvalidOperationException("Password must be at least 12 characters.");
        if (!password.Any(char.IsUpper))
            throw new InvalidOperationException("Password must contain at least one uppercase letter.");
        if (!password.Any(char.IsLower))
            throw new InvalidOperationException("Password must contain at least one lowercase letter.");
        if (!password.Any(char.IsDigit))
            throw new InvalidOperationException("Password must contain at least one digit.");
        if (!password.Any(c => !char.IsLetterOrDigit(c)))
            throw new InvalidOperationException("Password must contain at least one special character.");
    }
}
